description: This is a configuration file for running Task 8, Phase 2 analysis
ecm_prep:
  ecm_directory: null
  ecm_files:
    - Best Res. ASHP, Env., PC (EE+DF-FS) CC
    - Best Res. ASHP, Env., PC (EE+DF-FS)
    - Best Res. ASHP, Env., PC (EE+DF-LFL) CC
    - Best Res. ASHP, Env., PC (EE+DF-LFL)
    - Best Res. ASHP, Env., PC (EE+DF-RST) CC
    - Best Res. ASHP, Env., PC (EE+DF-RST)
    - Best Res. Fossil Heating
    - Best Res. GSHP (FS)
    - Best Res. GSHP (LFL)
    - Best Res. GSHP (RST)
    - Best Res. HPWH (EE+DF)
    - Best Res. HPWH (EE+DF-FS)
    - Best Residential Gas Storage WH
    - Best Residential Oil WH
    - ENERGY STAR Gas Storage WH v. 5.0
    - ENERGY STAR Res. ASHP (FS) CC
    - ENERGY STAR Res. ASHP (FS)
    - ENERGY STAR Res. ASHP (LFL) CC
    - ENERGY STAR Res. ASHP (LFL)
    - ENERGY STAR Res. ASHP (RST) CC
    - ENERGY STAR Res. ASHP (RST)
    - ENERGY STAR Res. GSHP (FS)
    - ENERGY STAR Res. GSHP (LFL)
    - ENERGY STAR Res. GSHP (RST)
    - ENERGY STAR Res. HPWH (FS) 120V
    - ENERGY STAR Res. HPWH (FS) 240V
    - ENERGY STAR Res. HPWH (FS) New
    - ENERGY STAR Res. HPWH
    - Min. Eff. Res. ASHP (FS) CC
    - Min. Eff. Res. ASHP (FS)
    - Min. Eff. Res. ASHP (RST) CC
    - Min. Eff. Res. ASHP (RST)
    - Prospective Residential ASHP (FS) CC
    - Prospective Residential ASHP (FS)
    - Prospective Residential ASHP (LFL) CC
    - Prospective Residential ASHP (LFL)
    - Prospective Residential ASHP (RST) CC
    - Prospective Residential ASHP (RST)
    - Prospective Residential HPWH (FS)
    - Prospective Residential HPWH
    - Ref. Case Res. Oil WH
    - Res. Fossil Heating, ESTAR (2030)
    - Res. Fossil Heating, ESTAR
  ecm_files_regex: []
  ecm_packages: []
  site_energy: false
  captured_energy: false
  alt_regions: EMM
  sect_shapes: false
  rp_persist: false
  verbose: false
  health_costs: false
  split_fuel: false
  no_scnd_lgt: false
  floor_start: null
  pkg_env_costs: null
  alt_ref_carb: false
  adopt_scn_restrict: Max adoption potential
  add_typ_eff: false
  pkg_env_sep: false
  detail_brkout: []
  fugitive_emissions: []
  tsv_metrics:
    tsv_type: null
    tsv_daily_hr_restrict: null
    tsv_sys_shape_case: null
    tsv_season: null
    tsv_energy_agg: null
    tsv_power_agg: null
    tsv_average_days: null
  exog_hp_rates:
    exog_hp_rate_scenario: null
    switch_all_retrofit_hp: false
  grid_decarb:
    grid_decarb_level: null
    grid_assesment_timing: null
  retrofits:
    retrofit_type: null
    retrofit_multiplier: null
    retrofit_mult_year: null
run:
  results_directory: null
  verbose: false
  mkt_fracs: true
  trim_results: false
  report_stk: true
  report_cfs: true
